name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 2.2.1
homepage: https://mehran.monster/

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  just_audio: ^0.10.4
  syncfusion_flutter_sliders: ">=25.1.41 <31.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


